# Generated by Django 4.0.4 on 2022-07-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='board',
        ),
        migrations.DeleteModel(
            name='Boards',
        ),
    ]
