# Generated by Django 4.0.4 on 2022-07-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='com_coment',
            new_name='com_comment',
        ),
    ]
