# Generated by Django 3.2.6 on 2022-07-23 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook_text', models.CharField(blank=True, help_text='simple one-line text.', max_length=100, verbose_name='HOOK_TEXT')),
                ('content', models.TextField(verbose_name='CONTENT')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='CREATED TIME')),
            ],
            options={
                'ordering': ('created_time',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_content', models.TextField(verbose_name='COM_CONTENT')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_TIME')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b_pj_app.post')),
            ],
        ),
    ]
