# Generated by Django 3.2.6 on 2022-07-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_pj_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hook_text',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='TITLE'),
        ),
    ]
