# Generated by Django 3.2.6 on 2022-07-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_pj_app', '0002_auto_20220723_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(default='', max_length=10),
        ),
    ]
